version: '3.8'

services:
  mysqldb:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: AUTHORIZATION
#      MYSQL_USER: 'devuser'
#      MYSQL_PASSWORD: 'devpass123'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
#      - ./docker-scripts/init:/docker-entrypoint-initdb.d
volumes:
  my-db: