spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AUTHORIZATION
    username: 'root'
    password: 'root'
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
jwt:
  key: '2a212126e981a493605cb80aa89c0e4c493589786ce8b0985baa1c6973c3c91d'
  access-token-expiration: 3600000